model_name: deepseek-ai/deepseek-llm-7b-base
dataset_name: meta-math/MetaMathQA
output_dir: output
num_epochs: 3
batch_size: 8
num_loops: 2
learning_rate: 5e-6
logging_steps: 100
save_steps: 5
eval_steps: 1
seed: 42
warmup_ratio: 0.1
max_data_length: 512